import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Plus, TrendingUp } from 'lucide-react'
import { useMemo, useState } from 'react'
import PageHeader from '../components/PageHeader'
import { useSaaSStore } from '../store/saasStore'
import { useToastStore } from '../store/uiStore'

const channelColor={Blog:'bg-brand-500',LinkedIn:'bg-sky-500',Email:'bg-violet-500',Instagram:'bg-pink-500'}
export default function CalendarPage(){
  const {events,addEvent}=useSaaSStore();const [cursor,setCursor]=useState(new Date(2026,5,1));const [open,setOpen]=useState(false);const [form,setForm]=useState({title:'',date:'2026-06-22',channel:'Blog',status:'Scheduled'});const addToast=useToastStore(s=>s.addToast)
  const year=cursor.getFullYear(),month=cursor.getMonth();const days=useMemo(()=>{const start=new Date(year,month,1).getDay();const total=new Date(year,month+1,0).getDate();return [...Array(start).fill(null),...Array.from({length:total},(_,i)=>i+1)]},[year,month]);const monthName=cursor.toLocaleDateString('en',{month:'long',year:'numeric'});const monthly=events.filter(x=>{const d=new Date(`${x.date}T00:00:00`);return d.getMonth()===month&&d.getFullYear()===year});
  const submit=e=>{e.preventDefault();addEvent(form);setOpen(false);setForm({...form,title:''});addToast('Content scheduled successfully.')}
  return <div className="space-y-6"><PageHeader eyebrow="Content Calendar" title="Plan the story before the deadline" description="Coordinate every channel, review stage, and publishing date from one calendar." actions={<button onClick={()=>setOpen(true)} className="btn-primary"><Plus size={16}/>Schedule content</button>}/><section className="grid gap-4 sm:grid-cols-3"><Metric label="Scheduled this month" value={monthly.length} icon={CalendarDays}/><Metric label="Publishing this week" value={events.filter(x=>x.status==='Scheduled').length} icon={Clock3}/><Metric label="Monthly output" value="+18%" icon={TrendingUp}/></section>
    <div className="grid gap-6 xl:grid-cols-[1fr_300px]"><section className="card overflow-hidden"><header className="flex items-center justify-between border-b p-4 sm:p-5"><div><h3 className="font-semibold">{monthName}</h3><p className="text-xs text-slate-500">{monthly.length} planned posts</p></div><div className="flex gap-1"><button onClick={()=>setCursor(new Date(year,month-1,1))} className="editor-tool"><ChevronLeft size={17}/></button><button onClick={()=>setCursor(new Date())} className="rounded-lg px-3 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-800">Today</button><button onClick={()=>setCursor(new Date(year,month+1,1))} className="editor-tool"><ChevronRight size={17}/></button></div></header><div className="grid grid-cols-7 border-b bg-slate-50 text-center text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:bg-slate-900">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><div key={x} className="py-3">{x}</div>)}</div><div className="grid grid-cols-7">{days.map((day,i)=>{const date=day?`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`:null;const dayEvents=events.filter(x=>x.date===date);return <div key={i} className={`min-h-24 border-b border-r p-1.5 sm:min-h-32 sm:p-2 ${!day?'bg-slate-50/50 dark:bg-slate-950/40':''}`}><span className={`grid h-6 w-6 place-items-center rounded-full text-xs ${date==='2026-06-20'?'bg-brand-600 font-semibold text-white':''}`}>{day}</span><div className="mt-1 space-y-1">{dayEvents.map(e=><div key={e.id} className="truncate rounded-md bg-slate-100 p-1 text-[9px] font-medium dark:bg-slate-800 sm:p-1.5 sm:text-[10px]"><i className={`mr-1 inline-block h-1.5 w-1.5 rounded-full ${channelColor[e.channel]||'bg-slate-400'}`}/>{e.title}</div>)}</div></div>})}</div></section>
      <aside className="space-y-4"><section className="card p-5"><h3 className="font-semibold">Upcoming posts</h3><div className="mt-4 space-y-4">{events.slice().sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5).map(e=><div key={e.id} className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-center dark:bg-slate-800"><span className="text-[9px] uppercase text-slate-400">{new Date(`${e.date}T00:00:00`).toLocaleDateString('en',{month:'short'})}</span><strong className="-mt-1 text-sm">{new Date(`${e.date}T00:00:00`).getDate()}</strong></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{e.title}</p><p className="text-xs text-slate-500">{e.channel} · {e.status}</p></div></div>)}</div></section><section className="rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold uppercase tracking-wider text-brand-100">June performance</p><p className="mt-3 text-3xl font-bold">87%</p><p className="mt-1 text-xs leading-5 text-slate-400">of planned content published on time</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[87%] rounded-full bg-gradient-to-r from-brand-500 to-violet-500"/></div></section></aside></div>
    {open&&<div className="modal-backdrop"><form onSubmit={submit} className="modal-panel"><h3 className="text-lg font-semibold">Schedule content</h3><p className="mt-1 text-sm text-slate-500">Add a draft to your publishing calendar.</p><label className="mt-5 block"><span className="label">Title</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="input" placeholder="Content title"/></label><div className="mt-4 grid grid-cols-2 gap-3"><label><span className="label">Publish date</span><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="input"/></label><label><span className="label">Channel</span><select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})} className="input"><option>Blog</option><option>LinkedIn</option><option>Email</option><option>Instagram</option></select></label></div><label className="mt-4 block"><span className="label">Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="input"><option>Draft</option><option>Review</option><option>Scheduled</option></select></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="btn-secondary">Cancel</button><button className="btn-primary">Add to calendar</button></div></form></div>}
  </div>}
function Metric({label,value,icon:Icon}){return <article className="card flex items-center gap-4 p-5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10"><Icon size={20}/></span><div><p className="text-2xl font-bold">{value}</p><p className="text-sm text-slate-500">{label}</p></div></article>}
