import { Archive, Download, Edit3, FileText, Heart, LoaderCircle, Search, Trash2, X } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import EmptyState from '../components/EmptyState'
import Loading from '../components/Loading'
import api, { errorMessage } from '../services/api'
import { useToastStore } from '../store/uiStore'
import { formatDate, typeLabel } from '../utils/format'

const types = ['all','blog','linkedin','instagram','email','resume','seo','product','youtube']

export default function LibraryPage() {
  const [params] = useSearchParams(); const requestedId = params.get('id')
  const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [type,setType]=useState('all'); const [view,setView]=useState('active'); const [selected,setSelected]=useState(null); const [saving,setSaving]=useState(false)
  const addToast=useToastStore(s=>s.addToast)
  const load=useCallback(async()=>{setLoading(true);try{const {data}=await api.get('/content',{params:{search:search||undefined,content_type:type,archived:view==='archived'}});setItems(data.items);if(requestedId){const found=data.items.find(x=>String(x.id)===requestedId);if(found)setSelected(found)}}catch(e){addToast(errorMessage(e),'error')}finally{setLoading(false)}},[search,type,view,requestedId,addToast])
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load])
  const patch=async(item,changes,message)=>{try{const {data}=await api.put(`/content/${item.id}`,changes);setItems(xs=>xs.map(x=>x.id===item.id?data:x));if(selected?.id===item.id)setSelected(data);addToast(message)}catch(e){addToast(errorMessage(e),'error')}}
  const remove=async(item)=>{if(!window.confirm(`Delete “${item.title}” permanently?`))return;try{await api.delete(`/content/${item.id}`);setItems(xs=>xs.filter(x=>x.id!==item.id));setSelected(null);addToast('Content deleted.')}catch(e){addToast(errorMessage(e),'error')}}
  const saveEdit=async()=>{setSaving(true);await patch(selected,{title:selected.title,generated_text:selected.generated_text},'Changes saved.');setSaving(false)}
  const exportFile=async(format)=>{try{const response=await api.post(`/export/${format}`,{title:selected.title,text:selected.generated_text},{responseType:'blob'});const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download=`${selected.title}.${format}`;a.click();URL.revokeObjectURL(url);addToast(`${format.toUpperCase()} downloaded.`)}catch(e){addToast(errorMessage(e),'error')}}
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold tracking-tight">Content library</h2><p className="mt-1 text-sm text-slate-500">Search, refine, export, and organize your work.</p></div><div className="flex rounded-xl border bg-white p-1 text-sm dark:bg-slate-900"><button onClick={()=>setView('active')} className={`rounded-lg px-3 py-1.5 ${view==='active'?'bg-slate-100 font-semibold dark:bg-slate-800':''}`}>Active</button><button onClick={()=>setView('archived')} className={`rounded-lg px-3 py-1.5 ${view==='archived'?'bg-slate-100 font-semibold dark:bg-slate-800':''}`}>Archived</button></div></div><div className="card flex flex-col gap-3 p-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input className="input pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search titles, prompts, and content..."/></label><select className="input sm:w-44" value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t} value={t}>{t==='all'?'All formats':typeLabel(t)}</option>)}</select></div>
    {loading?<Loading label="Loading your library..."/>:items.length===0?<EmptyState title="No content found" message={search?'Try a different search or filter.':'Generated content you save will appear here.'}/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(item=><article key={item.id} className="card group p-5"><div className="flex items-start justify-between gap-3"><span className="rounded-lg bg-brand-50 px-2 py-1 text-[11px] font-semibold text-brand-700 dark:bg-brand-500/10 dark:text-brand-100">{typeLabel(item.content_type)}</span><button onClick={()=>patch(item,{is_favorite:!item.is_favorite},item.is_favorite?'Removed from favorites.':'Added to favorites.')} className={item.is_favorite?'text-rose-500':'text-slate-300 hover:text-rose-500'}><Heart size={18} fill={item.is_favorite?'currentColor':'none'}/></button></div><h3 className="mt-4 truncate font-semibold">{item.title}</h3><p className="mt-2 line-clamp-3 min-h-[60px] text-sm leading-5 text-slate-500">{item.generated_text}</p><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="text-xs text-slate-400">{formatDate(item.updated_at)}</span><div className="flex gap-1"><button className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-slate-800" onClick={()=>setSelected(item)} title="Edit"><Edit3 size={16}/></button><button className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-slate-800" onClick={()=>patch(item,{is_archived:!item.is_archived},item.is_archived?'Restored content.':'Content archived.')} title="Archive"><Archive size={16}/></button><button className="rounded-lg p-2 text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-500/10" onClick={()=>remove(item)} title="Delete"><Trash2 size={16}/></button></div></div></article>)}</div>}
    {selected&&<div className="fixed inset-0 z-50 flex items-end justify-end bg-black/45"><button className="absolute inset-0" onClick={()=>setSelected(null)} aria-label="Close editor"/><aside className="relative flex h-[92vh] w-full flex-col bg-white shadow-2xl dark:bg-slate-900 sm:h-full sm:max-w-2xl"><header className="flex items-center justify-between border-b p-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-brand-600">{typeLabel(selected.content_type)}</p><p className="text-sm text-slate-500">Last updated {formatDate(selected.updated_at)}</p></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="scrollbar flex-1 space-y-4 overflow-auto p-5 sm:p-7"><label><span className="label">Title</span><input className="input text-lg font-semibold" value={selected.title} onChange={e=>setSelected({...selected,title:e.target.value})}/></label><label><span className="label">Content</span><textarea className="input min-h-[55vh] resize-y leading-7" value={selected.generated_text} onChange={e=>setSelected({...selected,generated_text:e.target.value})}/></label></div><footer className="flex flex-wrap justify-between gap-3 border-t p-4"><div className="flex gap-2"><button onClick={()=>exportFile('pdf')} className="btn-secondary px-3"><Download size={16}/> PDF</button><button onClick={()=>exportFile('txt')} className="btn-secondary px-3"><FileText size={16}/> TXT</button></div><button onClick={saveEdit} disabled={saving} className="btn-primary">{saving&&<LoaderCircle className="animate-spin" size={16}/>} Save changes</button></footer></aside></div>}
  </div>
}
