import { Check, Clock3, Copy, Link2, MessageSquare, MoreHorizontal, Plus, Send, UserPlus, Users } from 'lucide-react'
import { useState } from 'react'
import PageHeader from '../components/PageHeader'
import { useSaaSStore } from '../store/saasStore'
import { useToastStore } from '../store/uiStore'

export default function TeamPage() {
  const { members, comments, inviteMember, addComment, toggleComment } = useSaaSStore()
  const [inviteOpen,setInviteOpen]=useState(false); const [email,setEmail]=useState(''); const [role,setRole]=useState('Editor'); const [comment,setComment]=useState(''); const addToast=useToastStore(s=>s.addToast)
  const invite=(e)=>{e.preventDefault();inviteMember(email,role);setEmail('');setInviteOpen(false);addToast('Workspace invitation sent.')}
  const post=(e)=>{e.preventDefault();if(!comment.trim())return;addComment(comment);setComment('');addToast('Comment added.')}
  const copyLink=()=>{navigator.clipboard.writeText(window.location.origin+'/shared/workspace');addToast('Share link copied.')}
  return <div className="space-y-6"><PageHeader eyebrow="Collaboration" title="One workspace, shared momentum" description="Invite teammates, share content, resolve feedback, and keep every decision visible." actions={<><button onClick={copyLink} className="btn-secondary"><Link2 size={16}/>Copy share link</button><button onClick={()=>setInviteOpen(true)} className="btn-primary"><UserPlus size={16}/>Invite member</button></>}/>
    <section className="grid gap-4 sm:grid-cols-3"><Metric icon={Users} value={members.length} label="Workspace members" color="brand"/><Metric icon={MessageSquare} value={comments.filter(c=>!c.resolved).length} label="Open comments" color="amber"/><Metric icon={Clock3} value="12" label="Updates this week" color="emerald"/></section>
    <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><section className="card overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h3 className="font-semibold">Members</h3><p className="text-sm text-slate-500">People with access to the ContentOS workspace</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{members.filter(x=>x.status==='active').length} active</span></div><div className="divide-y">{members.map(member=><div key={member.id} className="flex items-center gap-3 p-4 sm:p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-gradient-to-br from-brand-500 to-violet-600 text-xs font-bold text-white">{member.avatar}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{member.name}</p><p className="truncate text-xs text-slate-500">{member.email}</p></div><span className={`hidden rounded-full px-2.5 py-1 text-xs font-medium sm:block ${member.status==='invited'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300'}`}>{member.status==='invited'?'Invited':member.role}</span><button className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><MoreHorizontal size={17}/></button></div>)}</div></section>
      <section className="card flex min-h-[520px] flex-col overflow-hidden"><div className="border-b p-5"><h3 className="font-semibold">Comments</h3><p className="text-sm text-slate-500">Feedback on the active draft</p></div><div className="scrollbar flex-1 space-y-4 overflow-auto p-4">{comments.map(item=><article key={item.id} className={`rounded-xl border p-3.5 ${item.resolved?'opacity-60':''}`}><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-semibold">{item.author}</p><p className="mt-1 text-xs leading-5 text-slate-600 dark:text-slate-300">{item.text}</p></div><button onClick={()=>toggleComment(item.id)} className={`grid h-6 w-6 shrink-0 place-items-center rounded-full border ${item.resolved?'border-emerald-500 bg-emerald-500 text-white':'text-slate-300'}`} title="Resolve"><Check size={13}/></button></div><p className="mt-2 text-[10px] text-slate-400">{new Date(item.createdAt).toLocaleString()}</p></article>)}</div><form onSubmit={post} className="flex gap-2 border-t p-3"><input value={comment} onChange={e=>setComment(e.target.value)} className="input" placeholder="Add a comment…"/><button className="btn-primary px-3"><Send size={16}/></button></form></section></div>
    <section className="card p-5"><h3 className="font-semibold">Workspace activity</h3><div className="mt-5 grid gap-4 md:grid-cols-3">{['Maya commented on Product launch article','Alex scheduled June product digest','Noah resolved feedback on Founder story'].map((text,i)=><div key={text} className="flex gap-3"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-brand-500 ring-4 ring-brand-50 dark:ring-brand-500/10"/><div><p className="text-sm font-medium">{text}</p><p className="mt-1 text-xs text-slate-400">{i+1}h ago</p></div></div>)}</div></section>
    {inviteOpen&&<div className="modal-backdrop"><form onSubmit={invite} className="modal-panel"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-brand-50 text-brand-600"><UserPlus size={20}/></span><div><h3 className="font-semibold">Invite to workspace</h3><p className="text-xs text-slate-500">They will receive an email invitation.</p></div></div><label className="mt-5 block"><span className="label">Email address</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="input" placeholder="teammate@company.com"/></label><label className="mt-4 block"><span className="label">Workspace role</span><select value={role} onChange={e=>setRole(e.target.value)} className="input"><option>Editor</option><option>Viewer</option><option>Admin</option></select></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setInviteOpen(false)} className="btn-secondary">Cancel</button><button className="btn-primary">Send invitation</button></div></form></div>}
  </div>
}
function Metric({icon:Icon,value,label,color}){const c={brand:'bg-brand-50 text-brand-600 dark:bg-brand-500/10',amber:'bg-amber-50 text-amber-600 dark:bg-amber-500/10',emerald:'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10'}[color];return <article className="card flex items-center gap-4 p-5"><span className={`grid h-11 w-11 place-items-center rounded-xl ${c}`}><Icon size={20}/></span><div><p className="text-2xl font-bold">{value}</p><p className="text-sm text-slate-500">{label}</p></div></article>}
